/* ================================================
   mockData.js — Données de démonstration
   FHG Tracker
   ================================================ */

/**
 * Données mock utilisées quand aucune clé API n'est configurée.
 * Correspond exactement aux 5 matchs de référence du cahier des charges.
 */

export const MOCK_DATA = {

  // ---- MATCHS DU JOUR ----
  matches: [
    {
      id: 'mock_1',
      homeID: 101,
      awayID: 102,
      homeName: 'Bayern Munich',
      awayName: 'Borussia Dortmund',
      leagueName: 'Bundesliga',
      leagueId: 'bundesliga',
      leagueFlag: '🇩🇪',
      time: '20:30',
      date: getTodayStr(),
      status: 'upcoming',
      context: 'DOM',
    },
    {
      id: 'mock_2',
      homeID: 103,
      awayID: 104,
      homeName: 'Bayer Leverkusen',
      awayName: 'RB Leipzig',
      leagueName: 'Bundesliga',
      leagueId: 'bundesliga',
      leagueFlag: '🇩🇪',
      time: '18:30',
      date: getTodayStr(),
      status: 'upcoming',
      context: 'DOM',
    },
    {
      id: 'mock_3',
      homeID: 201,
      awayID: 202,
      homeName: 'Brentford',
      awayName: 'Arsenal',
      leagueName: 'Premier League',
      leagueId: 'premier-league',
      leagueFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      time: '15:00',
      date: getTodayStr(),
      status: 'upcoming',
      context: 'DOM',
    },
    {
      id: 'mock_4',
      homeID: 203,
      awayID: 204,
      homeName: 'Wolverhampton',
      awayName: 'Chelsea',
      leagueName: 'Premier League',
      leagueId: 'premier-league',
      leagueFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      time: '17:30',
      date: getTodayStr(),
      status: 'upcoming',
      context: 'DOM',
    },
    {
      id: 'mock_5',
      homeID: 301,
      awayID: 302,
      homeName: 'RC Lens',
      awayName: 'PSG',
      leagueName: 'Ligue 1',
      leagueId: 'ligue-1',
      leagueFlag: '🇫🇷',
      time: '21:00',
      date: getTodayStr(),
      status: 'upcoming',
      context: 'DOM',
    },
  ],

  // ---- DONNÉES ÉQUIPES ----
  teams: {
    'bundesliga': [
      {
        id: 101,
        name: 'Bayern Munich',
        matches_played: 26,
        matches_played_n1: 34,
        goals_scored_min_31_to_45: 21,
        goals_scored_min_31_to_45_n1: 22,
        buts_31_45_sur_5_derniers: 4,
        matches_scored_first_half: 20,
        pct_retour_si_encaisse: 72,
        pct_victoire_domicile: 82,
        dist_buts: { '0-15': 8, '16-30': 12, '31-45': 21, '46-60': 14, '61-75': 18, '76-90': 16 },
      },
      {
        id: 102,
        name: 'Borussia Dortmund',
        matches_played: 26,
        matches_played_n1: 34,
        goals_scored_min_31_to_45: 14,
        goals_scored_min_31_to_45_n1: 15,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 17,
        pct_retour_si_encaisse: 60,
        pct_victoire_domicile: 65,
        dist_buts: { '0-15': 6, '16-30': 9, '31-45': 14, '46-60': 10, '61-75': 13, '76-90': 11 },
      },
      {
        id: 103,
        name: 'Bayer Leverkusen',
        matches_played: 26,
        matches_played_n1: 34,
        goals_scored_min_31_to_45: 19,
        goals_scored_min_31_to_45_n1: 20,
        buts_31_45_sur_5_derniers: 4,
        matches_scored_first_half: 18,
        pct_retour_si_encaisse: 68,
        pct_victoire_domicile: 78,
        dist_buts: { '0-15': 7, '16-30': 11, '31-45': 19, '46-60': 13, '61-75': 16, '76-90': 14 },
      },
      {
        id: 104,
        name: 'RB Leipzig',
        matches_played: 26,
        matches_played_n1: 34,
        goals_scored_min_31_to_45: 13,
        goals_scored_min_31_to_45_n1: 14,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 15,
        pct_retour_si_encaisse: 55,
        pct_victoire_domicile: 60,
        dist_buts: { '0-15': 5, '16-30': 8, '31-45': 13, '46-60': 9, '61-75': 12, '76-90': 10 },
      },
    ],
    'premier-league': [
      {
        id: 201,
        name: 'Brentford',
        matches_played: 28,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 19,
        goals_scored_min_31_to_45_n1: 18,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 18,
        pct_retour_si_encaisse: 58,
        pct_victoire_domicile: 58,
        dist_buts: { '0-15': 7, '16-30': 10, '31-45': 19, '46-60': 11, '61-75': 14, '76-90': 12 },
      },
      {
        id: 202,
        name: 'Arsenal',
        matches_played: 28,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 14,
        goals_scored_min_31_to_45_n1: 15,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 17,
        pct_retour_si_encaisse: 50,
        pct_victoire_domicile: 68,
        dist_buts: { '0-15': 6, '16-30': 9, '31-45': 14, '46-60': 10, '61-75': 12, '76-90': 11 },
      },
      {
        id: 203,
        name: 'Wolverhampton',
        matches_played: 28,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 22,
        goals_scored_min_31_to_45_n1: 21,
        buts_31_45_sur_5_derniers: 4,
        matches_scored_first_half: 20,
        pct_retour_si_encaisse: 62,
        pct_victoire_domicile: 55,
        dist_buts: { '0-15': 8, '16-30': 11, '31-45': 22, '46-60': 13, '61-75': 15, '76-90': 12 },
      },
      {
        id: 204,
        name: 'Chelsea',
        matches_played: 28,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 15,
        goals_scored_min_31_to_45_n1: 16,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 16,
        pct_retour_si_encaisse: 55,
        pct_victoire_domicile: 65,
        dist_buts: { '0-15': 6, '16-30': 9, '31-45': 15, '46-60': 11, '61-75': 13, '76-90': 12 },
      },
    ],
    'ligue-1': [
      {
        id: 301,
        name: 'RC Lens',
        matches_played: 27,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 19,
        goals_scored_min_31_to_45_n1: 18,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 15,
        pct_retour_si_encaisse: 56,
        pct_victoire_domicile: 60,
        dist_buts: { '0-15': 6, '16-30': 9, '31-45': 19, '46-60': 10, '61-75': 13, '76-90': 11 },
      },
      {
        id: 302,
        name: 'PSG',
        matches_played: 27,
        matches_played_n1: 38,
        goals_scored_min_31_to_45: 16,
        goals_scored_min_31_to_45_n1: 18,
        buts_31_45_sur_5_derniers: 3,
        matches_scored_first_half: 18,
        pct_retour_si_encaisse: 45,
        pct_victoire_domicile: 80,
        dist_buts: { '0-15': 7, '16-30': 10, '31-45': 16, '46-60': 12, '61-75': 15, '76-90': 14 },
      },
    ],
  },

  // ---- H2H ----
  h2h: {
    '101_102': [
      { date: '2025-11-02', homeGoals: 3, awayGoals: 1, homeGoals_HT: 2, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:18,scored:true},{minute:38,scored:true},{minute:42,scored:false},{minute:74,scored:true}] },
      { date: '2025-04-06', homeGoals: 2, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:33,scored:true},{minute:56,scored:true},{minute:68,scored:false},{minute:83,scored:false}] },
      { date: '2024-11-03', homeGoals: 4, awayGoals: 0, homeGoals_HT: 2, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:22,scored:true},{minute:41,scored:true},{minute:63,scored:true},{minute:82,scored:true}] },
      { date: '2024-04-01', homeGoals: 0, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Bayern Munich',
        goals: [{minute:40,scored:false},{minute:71,scored:false}] },
      { date: '2023-11-05', homeGoals: 3, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:34,scored:true},{minute:58,scored:false},{minute:72,scored:true},{minute:85,scored:true}] },
    ],
    '102_101': [
      { date: '2025-11-02', homeGoals: 3, awayGoals: 1, homeGoals_HT: 2, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:18,scored:true},{minute:38,scored:true},{minute:42,scored:false},{minute:74,scored:true}] },
      { date: '2025-04-06', homeGoals: 2, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:33,scored:true},{minute:56,scored:true},{minute:68,scored:false},{minute:83,scored:false}] },
      { date: '2024-11-03', homeGoals: 4, awayGoals: 0, homeGoals_HT: 2, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:22,scored:true},{minute:41,scored:true},{minute:63,scored:true},{minute:82,scored:true}] },
      { date: '2024-04-01', homeGoals: 0, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Bayern Munich',
        goals: [{minute:40,scored:false},{minute:71,scored:false}] },
      { date: '2023-11-05', homeGoals: 3, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayern Munich',
        goals: [{minute:34,scored:true},{minute:58,scored:false},{minute:72,scored:true},{minute:85,scored:true}] },
    ],
    '103_104': [
      { date: '2025-10-20', homeGoals: 2, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:28,scored:true},{minute:42,scored:false},{minute:67,scored:true}] },
      { date: '2025-03-15', homeGoals: 3, awayGoals: 2, homeGoals_HT: 2, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:12,scored:true},{minute:39,scored:true},{minute:54,scored:true},{minute:73,scored:false},{minute:88,scored:false}] },
      { date: '2024-10-22', homeGoals: 1, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:31,scored:true},{minute:79,scored:false}] },
      { date: '2024-03-10', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Bayer Leverkusen',
        goals: [{minute:65,scored:false}] },
      { date: '2023-11-12', homeGoals: 2, awayGoals: 0, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:36,scored:true},{minute:77,scored:true}] },
    ],
    '104_103': [
      { date: '2025-10-20', homeGoals: 2, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:28,scored:true},{minute:42,scored:false},{minute:67,scored:true}] },
      { date: '2025-03-15', homeGoals: 3, awayGoals: 2, homeGoals_HT: 2, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:12,scored:true},{minute:39,scored:true},{minute:54,scored:true},{minute:73,scored:false},{minute:88,scored:false}] },
      { date: '2024-10-22', homeGoals: 1, awayGoals: 1, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:31,scored:true},{minute:79,scored:false}] },
      { date: '2024-03-10', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Bayer Leverkusen',
        goals: [{minute:65,scored:false}] },
      { date: '2023-11-12', homeGoals: 2, awayGoals: 0, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Bayer Leverkusen',
        goals: [{minute:36,scored:true},{minute:77,scored:true}] },
    ],
    '201_202': [
      { date: '2025-10-05', homeGoals: 2, awayGoals: 3, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:24,scored:true},{minute:40,scored:false},{minute:56,scored:false},{minute:71,scored:true},{minute:84,scored:false}] },
      { date: '2025-02-22', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:37,scored:true},{minute:62,scored:false},{minute:79,scored:false}] },
      { date: '2024-09-28', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Brentford',
        goals: [{minute:68,scored:false}] },
      { date: '2024-02-11', homeGoals: 2, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Brentford',
        goals: [{minute:55,scored:true},{minute:74,scored:false},{minute:88,scored:true}] },
      { date: '2023-09-24', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:21,scored:true},{minute:44,scored:false},{minute:82,scored:false}] },
    ],
    '202_201': [
      { date: '2025-10-05', homeGoals: 2, awayGoals: 3, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:24,scored:true},{minute:40,scored:false},{minute:56,scored:false},{minute:71,scored:true},{minute:84,scored:false}] },
      { date: '2025-02-22', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:37,scored:true},{minute:62,scored:false},{minute:79,scored:false}] },
      { date: '2024-09-28', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Brentford',
        goals: [{minute:68,scored:false}] },
      { date: '2024-02-11', homeGoals: 2, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Brentford',
        goals: [{minute:55,scored:true},{minute:74,scored:false},{minute:88,scored:true}] },
      { date: '2023-09-24', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Brentford',
        goals: [{minute:21,scored:true},{minute:44,scored:false},{minute:82,scored:false}] },
    ],
    '203_204': [
      { date: '2025-10-19', homeGoals: 0, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:58,scored:false},{minute:81,scored:false}] },
      { date: '2025-04-05', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Wolverhampton',
        goals: [{minute:32,scored:true},{minute:66,scored:false},{minute:83,scored:false}] },
      { date: '2024-10-15', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:73,scored:false}] },
      { date: '2024-03-22', homeGoals: 2, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:41,scored:false},{minute:63,scored:true},{minute:77,scored:true},{minute:89,scored:false}] },
      { date: '2023-10-08', homeGoals: 1, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:38,scored:false},{minute:56,scored:false},{minute:72,scored:true},{minute:84,scored:false}] },
    ],
    '204_203': [
      { date: '2025-10-19', homeGoals: 0, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:58,scored:false},{minute:81,scored:false}] },
      { date: '2025-04-05', homeGoals: 1, awayGoals: 2, homeGoals_HT: 1, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: true,  equipeNom: 'Wolverhampton',
        goals: [{minute:32,scored:true},{minute:66,scored:false},{minute:83,scored:false}] },
      { date: '2024-10-15', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:73,scored:false}] },
      { date: '2024-03-22', homeGoals: 2, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:41,scored:false},{minute:63,scored:true},{minute:77,scored:true},{minute:89,scored:false}] },
      { date: '2023-10-08', homeGoals: 1, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'Wolverhampton',
        goals: [{minute:38,scored:false},{minute:56,scored:false},{minute:72,scored:true},{minute:84,scored:false}] },
    ],
    '301_302': [
      { date: '2025-09-28', homeGoals: 0, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:42,scored:false},{minute:57,scored:false},{minute:78,scored:false}] },
      { date: '2025-03-08', homeGoals: 1, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:61,scored:true},{minute:76,scored:false},{minute:88,scored:false}] },
      { date: '2024-10-20', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:69,scored:false}] },
      { date: '2024-01-15', homeGoals: 1, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:43,scored:false},{minute:58,scored:true},{minute:72,scored:false},{minute:85,scored:false}] },
    ],
    '302_301': [
      { date: '2025-09-28', homeGoals: 0, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:42,scored:false},{minute:57,scored:false},{minute:78,scored:false}] },
      { date: '2025-03-08', homeGoals: 1, awayGoals: 2, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:61,scored:true},{minute:76,scored:false},{minute:88,scored:false}] },
      { date: '2024-10-20', homeGoals: 0, awayGoals: 1, homeGoals_HT: 0, awayGoals_HT: 0, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:69,scored:false}] },
      { date: '2024-01-15', homeGoals: 1, awayGoals: 3, homeGoals_HT: 0, awayGoals_HT: 1, equipe_ciblee_but_avant_45min: false, equipeNom: 'RC Lens',
        goals: [{minute:43,scored:false},{minute:58,scored:true},{minute:72,scored:false},{minute:85,scored:false}] },
    ],
  },

  // ---- LIGUES DISPONIBLES ----
  leagues: [
    { id: 82,  name: 'Bundesliga',         country: 'Allemagne', flag: '🇩🇪' },
    { id: 8,   name: 'Premier League',      country: 'Angleterre',flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    { id: 168, name: 'Ligue 1',             country: 'France',    flag: '🇫🇷' },
    { id: 302, name: 'Eredivisie',          country: 'Pays-Bas',  flag: '🇳🇱' },
    { id: 9,   name: 'Championship',        country: 'Angleterre',flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    { id: 203, name: 'Süper Lig',           country: 'Turquie',   flag: '🇹🇷' },
    { id: 87,  name: 'La Liga',             country: 'Espagne',   flag: '🇪🇸' },
    { id: 384, name: 'Serie A',             country: 'Italie',    flag: '🇮🇹' },
  ],

  leagueMatches: {},
  matchDetails: {},
};

function getTodayStr() {
  return new Date().toISOString().split('T')[0];
}

// ---- HISTORIQUE DES ALERTES (mock) ----

export const mockAlertHistory = [
  // --- Premier League ---
  { id: 'mock-1', match_date: '2025-03-15', home_team: 'Manchester City', away_team: 'Arsenal', league_name: 'Premier League', signal_type: 'FHG', fhg_score: 78, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-15T15:00:00Z', result: 'goal', goal_minute: 38, expected_window: '31-45', notes: 'But à la 38e minute, dans la fenêtre', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-2', match_date: '2025-03-16', home_team: 'Liverpool', away_team: 'Chelsea', league_name: 'Premier League', signal_type: 'BOTH', fhg_score: 82, dc_score: 75, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-16T14:00:00Z', result: 'goal', goal_minute: 33, expected_window: '31-45', notes: 'But 33e, pile dans la fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-3', match_date: '2025-03-22', home_team: 'Tottenham', away_team: 'Aston Villa', league_name: 'Premier League', signal_type: 'FHG', fhg_score: 65, dc_score: null, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-03-22T15:00:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: '0-0 à la MT, aucun but 1MT', tags: ['FHG', 'H2H orange'] },
  { id: 'mock-4', match_date: '2025-04-02', home_team: 'Newcastle', away_team: 'Wolverhampton', league_name: 'Premier League', signal_type: 'DC', fhg_score: null, dc_score: 80, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-04-02T19:45:00Z', result: 'goal', goal_minute: null, expected_window: null, notes: 'DC validé, victoire 2-0', tags: ['DC', 'H2H vert'] },
  { id: 'mock-5', match_date: '2025-04-06', home_team: 'Brighton', away_team: 'Brentford', league_name: 'Premier League', signal_type: 'FHG', fhg_score: 71, dc_score: null, h2h_status: 'insufficient', has_1mt_bonus: true, kickoff_time: '2025-04-06T14:00:00Z', result: 'goal', goal_minute: 41, expected_window: '31-45', notes: 'But 41e, fenêtre validée', tags: ['FHG', '1MT'] },
  { id: 'mock-6', match_date: '2025-04-12', home_team: 'West Ham', away_team: 'Everton', league_name: 'Premier League', signal_type: 'FHG', fhg_score: 62, dc_score: null, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-04-12T15:00:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: 'Match fermé, 0-0 MT', tags: ['FHG', 'H2H orange'] },
  { id: 'mock-7', match_date: '2025-04-20', home_team: 'Arsenal', away_team: 'Manchester United', league_name: 'Premier League', signal_type: 'BOTH', fhg_score: 85, dc_score: 82, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-04-20T16:30:00Z', result: 'goal', goal_minute: 28, expected_window: '31-45', notes: 'But 28e — hors fenêtre mais avant MT', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },

  // --- La Liga ---
  { id: 'mock-8', match_date: '2025-03-16', home_team: 'Barcelona', away_team: 'Real Madrid', league_name: 'La Liga', signal_type: 'BOTH', fhg_score: 88, dc_score: 85, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-16T20:00:00Z', result: 'goal', goal_minute: 22, expected_window: '31-45', notes: 'But 22e, avant fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-9', match_date: '2025-03-23', home_team: 'Atletico Madrid', away_team: 'Sevilla', league_name: 'La Liga', signal_type: 'DC', fhg_score: null, dc_score: 72, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-03-23T18:30:00Z', result: 'goal', goal_minute: null, expected_window: null, notes: 'DC solide, victoire 1-0', tags: ['DC', 'H2H vert'] },
  { id: 'mock-10', match_date: '2025-04-06', home_team: 'Real Sociedad', away_team: 'Athletic Bilbao', league_name: 'La Liga', signal_type: 'FHG', fhg_score: 67, dc_score: null, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-04-06T16:15:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: 'Derby basque, 0-0 MT', tags: ['FHG', 'H2H orange'] },
  { id: 'mock-11', match_date: '2025-04-13', home_team: 'Villarreal', away_team: 'Betis', league_name: 'La Liga', signal_type: 'FHG', fhg_score: 74, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-04-13T20:00:00Z', result: 'goal', goal_minute: 36, expected_window: '31-45', notes: 'But 36e penalty, dans la fenêtre', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-12', match_date: '2025-04-27', home_team: 'Valencia', away_team: 'Celta Vigo', league_name: 'La Liga', signal_type: 'DC', fhg_score: null, dc_score: 68, h2h_status: 'insufficient', has_1mt_bonus: false, kickoff_time: '2025-04-27T18:30:00Z', result: null, goal_minute: null, expected_window: null, notes: '', tags: ['DC'] },

  // --- Bundesliga ---
  { id: 'mock-13', match_date: '2025-03-15', home_team: 'Bayern Munich', away_team: 'Borussia Dortmund', league_name: 'Bundesliga', signal_type: 'BOTH', fhg_score: 90, dc_score: 88, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-15T18:30:00Z', result: 'goal', goal_minute: 18, expected_window: '31-45', notes: 'But 18e, bien avant fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-14', match_date: '2025-03-22', home_team: 'Bayer Leverkusen', away_team: 'RB Leipzig', league_name: 'Bundesliga', signal_type: 'FHG', fhg_score: 76, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-22T15:30:00Z', result: 'goal', goal_minute: 31, expected_window: '31-45', notes: 'But 31e Wirtz, pile début fenêtre', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-15', match_date: '2025-04-05', home_team: 'Eintracht Frankfurt', away_team: 'Stuttgart', league_name: 'Bundesliga', signal_type: 'FHG', fhg_score: 63, dc_score: null, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-04-05T15:30:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: 'Pas de but 1MT', tags: ['FHG', 'H2H orange'] },
  { id: 'mock-16', match_date: '2025-04-19', home_team: 'Wolfsburg', away_team: 'Freiburg', league_name: 'Bundesliga', signal_type: 'DC', fhg_score: null, dc_score: 70, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-04-19T15:30:00Z', result: 'goal', goal_minute: null, expected_window: null, notes: 'DC validé 2-1', tags: ['DC', 'H2H vert'] },
  { id: 'mock-17', match_date: '2025-05-03', home_team: 'Borussia Dortmund', away_team: 'Union Berlin', league_name: 'Bundesliga', signal_type: 'FHG', fhg_score: 69, dc_score: null, h2h_status: 'insufficient', has_1mt_bonus: true, kickoff_time: '2025-05-03T18:30:00Z', result: 'goal', goal_minute: 44, expected_window: '31-45', notes: 'But 44e in extremis, dans la fenêtre', tags: ['FHG', '1MT'] },

  // --- Serie A ---
  { id: 'mock-18', match_date: '2025-03-16', home_team: 'Inter Milan', away_team: 'AC Milan', league_name: 'Serie A', signal_type: 'BOTH', fhg_score: 80, dc_score: 78, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-16T20:45:00Z', result: 'goal', goal_minute: 25, expected_window: '31-45', notes: 'Derby, but 25e Lautaro, avant fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-19', match_date: '2025-03-30', home_team: 'Napoli', away_team: 'Roma', league_name: 'Serie A', signal_type: 'FHG', fhg_score: 72, dc_score: null, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-03-30T18:00:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: '0-0 à la pause', tags: ['FHG', 'H2H vert'] },
  { id: 'mock-20', match_date: '2025-04-13', home_team: 'Juventus', away_team: 'Lazio', league_name: 'Serie A', signal_type: 'DC', fhg_score: null, dc_score: 76, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-04-13T20:45:00Z', result: 'goal', goal_minute: null, expected_window: null, notes: 'DC validé, Juve solide 1-0', tags: ['DC', 'H2H vert'] },
  { id: 'mock-21', match_date: '2025-04-27', home_team: 'Atalanta', away_team: 'Fiorentina', league_name: 'Serie A', signal_type: 'FHG', fhg_score: 68, dc_score: null, h2h_status: 'orange', has_1mt_bonus: true, kickoff_time: '2025-04-27T15:00:00Z', result: 'goal', goal_minute: 40, expected_window: '31-45', notes: 'But 40e sur corner, dans la fenêtre', tags: ['FHG', '1MT', 'H2H orange'] },
  { id: 'mock-22', match_date: '2025-05-04', home_team: 'Roma', away_team: 'Torino', league_name: 'Serie A', signal_type: 'FHG', fhg_score: 61, dc_score: null, h2h_status: 'insufficient', has_1mt_bonus: false, kickoff_time: '2025-05-04T18:00:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: '0-0 MT, but 58e trop tard', tags: ['FHG'] },

  // --- Ligue 1 ---
  { id: 'mock-23', match_date: '2025-03-22', home_team: 'PSG', away_team: 'Marseille', league_name: 'Ligue 1', signal_type: 'BOTH', fhg_score: 84, dc_score: 80, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-03-22T21:00:00Z', result: 'goal', goal_minute: 15, expected_window: '31-45', notes: 'But 15e Dembélé, bien avant fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-24', match_date: '2025-03-30', home_team: 'Lyon', away_team: 'Monaco', league_name: 'Ligue 1', signal_type: 'FHG', fhg_score: 70, dc_score: null, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-03-30T20:45:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: 'Aucun but 1MT', tags: ['FHG', 'H2H orange'] },
  { id: 'mock-25', match_date: '2025-04-06', home_team: 'Lille', away_team: 'Nice', league_name: 'Ligue 1', signal_type: 'DC', fhg_score: null, dc_score: 73, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-04-06T17:05:00Z', result: 'goal', goal_minute: null, expected_window: null, notes: 'DC validé, victoire 2-0', tags: ['DC', 'H2H vert'] },
  { id: 'mock-26', match_date: '2025-04-20', home_team: 'RC Lens', away_team: 'Rennes', league_name: 'Ligue 1', signal_type: 'FHG', fhg_score: 66, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-04-20T15:00:00Z', result: 'goal', goal_minute: 42, expected_window: '31-45', notes: 'But 42e coup franc, dans la fenêtre', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-27', match_date: '2025-05-04', home_team: 'Strasbourg', away_team: 'Montpellier', league_name: 'Ligue 1', signal_type: 'FHG', fhg_score: 60, dc_score: null, h2h_status: 'insufficient', has_1mt_bonus: false, kickoff_time: '2025-05-04T15:00:00Z', result: null, goal_minute: null, expected_window: '31-45', notes: '', tags: ['FHG'] },

  // --- Entrées supplémentaires variées ---
  { id: 'mock-28', match_date: '2025-05-10', home_team: 'Manchester City', away_team: 'Liverpool', league_name: 'Premier League', signal_type: 'BOTH', fhg_score: 86, dc_score: 83, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-05-10T16:30:00Z', result: 'goal', goal_minute: 35, expected_window: '31-45', notes: 'But 35e Haaland, dans la fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-29', match_date: '2025-05-11', home_team: 'Real Madrid', away_team: 'Atletico Madrid', league_name: 'La Liga', signal_type: 'FHG', fhg_score: 75, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-05-11T21:00:00Z', result: 'no_goal', goal_minute: null, expected_window: '31-45', notes: 'Derby, 0-0 MT puis but 55e', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-30', match_date: '2025-05-17', home_team: 'Bayern Munich', away_team: 'Bayer Leverkusen', league_name: 'Bundesliga', signal_type: 'BOTH', fhg_score: 81, dc_score: 79, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-05-17T18:30:00Z', result: 'goal', goal_minute: 34, expected_window: '31-45', notes: 'But 34e Müller, dans la fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-31', match_date: '2025-05-18', home_team: 'AC Milan', away_team: 'Napoli', league_name: 'Serie A', signal_type: 'DC', fhg_score: null, dc_score: 74, h2h_status: 'orange', has_1mt_bonus: false, kickoff_time: '2025-05-18T20:45:00Z', result: 'no_goal', goal_minute: null, expected_window: null, notes: 'DC raté, défaite 1-2', tags: ['DC', 'H2H orange'] },
  { id: 'mock-32', match_date: '2025-05-24', home_team: 'PSG', away_team: 'Lyon', league_name: 'Ligue 1', signal_type: 'FHG', fhg_score: 77, dc_score: null, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-05-24T21:00:00Z', result: 'goal', goal_minute: 27, expected_window: '31-45', notes: 'But 27e Dembélé, avant fenêtre', tags: ['FHG', '1MT', 'H2H vert'] },
  { id: 'mock-33', match_date: '2025-05-25', home_team: 'Chelsea', away_team: 'Tottenham', league_name: 'Premier League', signal_type: 'FHG', fhg_score: 73, dc_score: null, h2h_status: 'green', has_1mt_bonus: false, kickoff_time: '2025-05-25T14:00:00Z', result: 'goal', goal_minute: 43, expected_window: '31-45', notes: 'But 43e, dans la fenêtre', tags: ['FHG', 'H2H vert'] },
  { id: 'mock-34', match_date: '2025-05-31', home_team: 'Barcelona', away_team: 'Villarreal', league_name: 'La Liga', signal_type: 'BOTH', fhg_score: 79, dc_score: 77, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-05-31T18:30:00Z', result: null, goal_minute: null, expected_window: '31-45', notes: '', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
  { id: 'mock-35', match_date: '2025-06-01', home_team: 'Inter Milan', away_team: 'Juventus', league_name: 'Serie A', signal_type: 'BOTH', fhg_score: 83, dc_score: 81, h2h_status: 'green', has_1mt_bonus: true, kickoff_time: '2025-06-01T20:45:00Z', result: 'goal', goal_minute: 19, expected_window: '31-45', notes: 'Derby d\'Italia, but 19e avant fenêtre', tags: ['FHG', 'DC', '1MT', 'H2H vert'] },
];

export const mockBacktestResults = {
  total_signals: 245,
  true_positives: 158,
  false_positives: 87,
  success_rate: 64.5,
  by_league: [
    { league: 'Premier League', signals: 48, wins: 33, rate: 68.75 },
    { league: 'La Liga', signals: 42, wins: 28, rate: 66.67 },
    { league: 'Bundesliga', signals: 38, wins: 25, rate: 65.79 },
    { league: 'Serie A', signals: 35, wins: 21, rate: 60.0 },
    { league: 'Ligue 1', signals: 32, wins: 19, rate: 59.38 },
  ],
  by_threshold: [
    { threshold: 50, signals: 380, rate: 55.2 },
    { threshold: 55, signals: 320, rate: 58.4 },
    { threshold: 60, signals: 245, rate: 64.5 },
    { threshold: 65, signals: 180, rate: 68.3 },
    { threshold: 70, signals: 120, rate: 72.1 },
    { threshold: 75, signals: 72, rate: 76.4 },
    { threshold: 80, signals: 35, rate: 80.0 },
  ],
  with_1mt_bonus: { signals: 95, rate: 71.6 },
  without_1mt_bonus: { signals: 150, rate: 59.3 },
  by_h2h: {
    green: { signals: 110, rate: 72.7 },
    orange: { signals: 80, rate: 58.8 },
    insufficient: { signals: 55, rate: 56.4 },
  }
};
